### PR TITLE
ROC-91 initial match profile

### PR DESCRIPTION
**Pull request by squaill**
image
will make perty in sprint 4

### CODE REVIEW

**Comment by LarrySchultheis** [comment]
Sure you're aware but there's some styling weirdness in the dropdowns on my profile, see screenshot. Also, the modal only pops up on a fresh reload of the page. If we're letting the user change things we should probably have some mechanism to allow them to trigger the modal popup again. Anyways merging for burndahn Screenshot 2023-07-23 at 12 19 07 PM

**Review by LarrySchultheis — APPROVED** [review]

**Comment by squaill** [comment]
> Sure you're aware but there's some styling weirdness in the dropdowns on my profile, see screenshot. Also, the modal only pops up on a fresh reload of the page. If we're letting the user change things we should probably have some mechanism to allow them to trigger the modal popup again. Anyways merging for burndahn Screenshot 2023-07-23 at 12 19 07 PM

ack on the styling weirdness. Added a ticket to address general UI funk next sprint. The modal pops up on reload if the user's match profile is incomplete. If they close it, they can still make changes on the match profile tab which I thought was sufficient. I'll add instructions to the modal to make it more clear that it's a "hey fill out your profile" kind of reminder.

**Comment by LarrySchultheis** [comment]
Sick. Are we still planning on allowing them to change name/gender? Didn't see that as part of this PR

**Comment by squaill** [comment]
name should be changeable now. Gender was irrelevant and I didn't feel like updating the User model so I just got rid of it

**Pull request merged**
